ESC script-message jellyfin-close
F11 script-message jellyfin-fullscreen
Ctrl+r script-message jellyfin-resync
LEFT script-message jellyfin-seek-relative -10
RIGHT script-message jellyfin-seek-relative 10
j script-message jellyfin-seek-relative -10
l script-message jellyfin-seek-relative 10
SPACE cycle pause
UP add volume 5
DOWN add volume -5
